### PR TITLE
Add jq and python-tabulate as deps, missing nginx conf, missing Roundcube IMAP/SMTP setup, fixing typos

### PR DESCRIPTION
**Pull request by HLFH**
`python-tabulate` is required for `make help`
`jq` is required for `make dev`

### CODE REVIEW

**Comment by HLFH** [comment]
Adding missing Roundcube IMAP/SMTP as well.

**Comment by HLFH** [comment]
Also fixing typos in README: RoundCube > Roundcube.

**Comment by HLFH** [comment]
@rotdrop Care merging that one? And releasing 1.0.3?

**Comment by HLFH** [comment]
I will keep my fork maintained and separate.

**Comment by rotdrop** [comment]
I am closing this now again after cherry-picking most of the changes. Thank you again!

**Pull request closed without merging**
